# Configure your game settings

width: 400
height: 300
canvas-id: game-canvas

#files to ignore in /scripts
scripts-ignore:
  
#specify files to be loaded first in /scripts
order:
  
#components to ignore in the entityjs source
#reduce file size by ignoring unused components
entity-ignore:
  socket
  wait
  group

#ignore tests in /tests
tests-ignore:
  